/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as ApiPublicCryptoWithdrawRecordTransactionRouteImport } from './routes/api/public/crypto-withdraw/record-transaction'
import { Route as ApiPublicCryptoWithdrawTransactionsRouteImport } from './routes/api/public/crypto-withdraw/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCryptoWithdrawRecordTransactionRoute =
  ApiPublicCryptoWithdrawRecordTransactionRouteImport.update({
    id: '/api/public/crypto-withdraw/record-transaction',
    path: '/api/public/crypto-withdraw/record-transaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCryptoWithdrawTransactionsRoute =
  ApiPublicCryptoWithdrawTransactionsRouteImport.update({
    id: '/api/public/crypto-withdraw/transactions',
    path: '/api/public/crypto-withdraw/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sdk': typeof SdkRoute
  '/api/public/crypto-withdraw/record-transaction': typeof ApiPublicCryptoWithdrawRecordTransactionRoute
  '/api/public/crypto-withdraw/transactions': typeof ApiPublicCryptoWithdrawTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sdk': typeof SdkRoute
  '/api/public/crypto-withdraw/record-transaction': typeof ApiPublicCryptoWithdrawRecordTransactionRoute
  '/api/public/crypto-withdraw/transactions': typeof ApiPublicCryptoWithdrawTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/sdk': typeof SdkRoute
  '/api/public/crypto-withdraw/record-transaction': typeof ApiPublicCryptoWithdrawRecordTransactionRoute
  '/api/public/crypto-withdraw/transactions': typeof ApiPublicCryptoWithdrawTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/sdk'
    | '/api/public/crypto-withdraw/record-transaction'
    | '/api/public/crypto-withdraw/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/sdk'
    | '/api/public/crypto-withdraw/record-transaction'
    | '/api/public/crypto-withdraw/transactions'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/sdk'
    | '/api/public/crypto-withdraw/record-transaction'
    | '/api/public/crypto-withdraw/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  SdkRoute: typeof SdkRoute
  ApiPublicCryptoWithdrawRecordTransactionRoute: typeof ApiPublicCryptoWithdrawRecordTransactionRoute
  ApiPublicCryptoWithdrawTransactionsRoute: typeof ApiPublicCryptoWithdrawTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto-withdraw/record-transaction': {
      id: '/api/public/crypto-withdraw/record-transaction'
      path: '/api/public/crypto-withdraw/record-transaction'
      fullPath: '/api/public/crypto-withdraw/record-transaction'
      preLoaderRoute: typeof ApiPublicCryptoWithdrawRecordTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crypto-withdraw/transactions': {
      id: '/api/public/crypto-withdraw/transactions'
      path: '/api/public/crypto-withdraw/transactions'
      fullPath: '/api/public/crypto-withdraw/transactions'
      preLoaderRoute: typeof ApiPublicCryptoWithdrawTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  SdkRoute: SdkRoute,
  ApiPublicCryptoWithdrawRecordTransactionRoute:
    ApiPublicCryptoWithdrawRecordTransactionRoute,
  ApiPublicCryptoWithdrawTransactionsRoute:
    ApiPublicCryptoWithdrawTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
